config/routes.rb
Pixtr::Application.routes.draw do

  root "homes#show"
  resource :dashboard, only: [:show]

  resources :galleries do
      member do
        post "vote" => "gallery_votes#create"
        delete "unvote" => "gallery_votes#destroy"
      end

      resources :images, only: [:new, :create]
  end

  resources :groups, only: [:index, :create, :new, :show] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
    member do
      post "vote" => "group_votes#create"
      delete "unvote" => "group_votes#destroy"
    end
 end

  resources :users, only: [:index, :show] do
    member do
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end

  resources :images, except: [:index, :new, :create] do
    member do
      post "vote" => "image_votes#create"
      delete "unvote" => "image_votes#destroy"
    end
 
    resources :comments, only: [:create]


   end
    resources :comments, only: [:destroy]
    resources :tags, only:[:show]

    resources :charges
    resource :search, only: [:show]
end

app/models/image.rb
class Image < ActiveRecord::Base
  acts_as_taggable

  belongs_to :gallery
  has_many :comments, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  has_many :activities

  has_many :group_images, dependent: :destroy
  has_many :groups, through: :group_images

  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true

  def user
    gallery.user
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  respond_to :html

  def new
    @gallery = current_user.galleries.find(params[:gallery_id])
    @image = Image.new
  end

  def create
    @gallery = current_user.galleries.find(params[:gallery_id])
    @image = @gallery.images.create(image_params)

    respond_with @image, location: @gallery
  end

  def show
    @image = Image.find(params[:id])
    @comment = Comment.new
    @comments = @image.comments.paginate(params[:page])
    @tags = @image.tags
  end

  def edit
    @image = current_user.images.find(params[:id])
    @groups = current_user.groups
  end

  def update
    @image = current_user.images.find(params[:id])
    if @image.update(image_params)
      redirect_to @image
    else
      @groups = current_user.groups
      render :edit
    end
  end

  def destroy
    image = current_user.images.find(params[:id])
    image.destroy
    redirect_to image.gallery
  end

  private

  def image_params
    params.require(:image).permit(:name, :description, :url, :tag_list, group_ids:[])
  end
end

app/views/images/_image.html.erb
<%= link_to image_tag(image.url, width: 200), image %>
<p>by <%= link_to image.user.email, image.user %>

app/views/images/_image_vote_button.html.erb
<% if current_user.voted? @image %> 
  <div id="image_vote_button">
    <%= button_to "Downvote", unvote_image_path(@image), method: :delete, remote: true %>
  </div>
<% else %>
  <div id="image_vote_button">
    <%= button_to "Upvote", vote_image_path(@image), remote: true %>
  </div>
<% end %>

app/views/images/_search.html.erb
<%= @images %>

app/views/images/edit.html.erb
<h1>Edit Image</h1>

<%= form_for(@image) do |form| %>
  <%= render 'form_errors', target: @image %>

  <div>Name: <%= form.text_field :name %> </div>
  <div>Description: <%= form.text_field :description %> </div>
  <div>URL:<%= form.text_field :url %></div>
  <div>Tags: <%= form.text_field :tag_list %> </div>

  <p>
    <div><%= form.collection_check_boxes :group_ids, @groups, :id, :name %>
    <%= form.submit "Update Image" %>
  </p>
<% end %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= form_for([@gallery, @image]) do |form| %>
  <%= render 'form_errors', target: @image %>

  <div> <%= form.text_field :name %> Name </div>
  <div> <%= form.text_field :description %> Description </div>
  <div> <%= form.text_field :url %> URL </div>

  <%= form.submit "Upload Image" %>

<% end %>

app/views/images/search.html.erb
<% @results.each do |image| %>
  <%= link_to image.name, image %>
<% end %>
hey
<%= render @images %>

app/views/images/show.html.erb
<h3> <%= @image.name %> </h3>
<div>
  <%= image_tag(@image.url, width: 300) %>
</div>
<div>
  <%= @image.description %>
</div>
<% if signed_in? %>
  <div id="image_vote_button">
  <%= render "image_vote_button", image: @image %>
</div>
<% end %>
<div>
  <%= pluralize(@image.votes.count, "upvotes") %> <br>
  uploaded by: <%= link_to @image.user.email, @image.user %>
on <%= @image.created_at.strftime("%B %d, %Y") %>
</div>

<div>
  Tags:
  <% @image.tag_list.each do |tag| %>
    <%= link_to tag, tag_path(tag) %>
<% end %>
</div>
<% if @image.user == current_user %>
  <div>
  <%= link_to "Edit Image", edit_image_path(@image) %>,
  <%= link_to "Delete Image", @image,
  method: :delete, confirm: "Are you sure you want to delete this image?" %>
  </div>
<% end %>

<div>
  <% if signed_in? %>
    <%= form_for([@image, @comment], remote: true) do |form| %>
    <%= form.text_area :body %>
    <%= form.submit "Comment" %>
<% end %>
<% else %>
    <%= link_to "Sign in", sign_in_path %> to comment
<% end %>
<div id="comments">
  <%= render @comments %>
</div>
  <%= paginate @comments %>
</div>